### PR TITLE
Feat(libraries): add Leaflet versions [1.0.1 - 1.0.3]

### PR DESCRIPTION
**Pull request by ghybs**
so that it is easier to make up live test cases and it avoids confusion about maintained / available versions.

Added versions: 1.0.1, 1.0.2, 1.0.3 (using unkpg.com CDN)

### CODE REVIEW

**Comment by IvanSanchez** [comment]
Looks good. Let me redeploy.

**Comment by IvanSanchez** [comment]
Apparently rebuilding the jsbin app fails, because my local nodejs v7 cannot resolve some old `node-gyp` stuff involving `fstream`.

On top of that, I tried rebasing everything on top of the latest jsbin, but that ultimately fails with a `Error: sqlite is not supported, only mysql as of v4.`. That would mean reconfiguring the whole rhcloud instance and losing all existing playgrounds (or migrating them somehow).

~~~Thus, **I have not been able to deploy this change**. @ghybs, I could really use some ideas here.~~~

**Comment by IvanSanchez** [comment]
OK, strike my last. I've found some my old built files, manually hacked the libraries in (see https://github.com/Leaflet/playground/commit/bc62ae41479728dc6ecbb117437958c7fa204fbe ), and redeployed just those files via manual `rsync`.

Maintaining this is becoming increasingly hackish, I'd appreciate some help. :-|

**Comment by ghybs** [comment]
Hi @IvanSanchez,

Indeed it looks like JS Bin dropped sqlite support when going to [`v4`](https://github.com/jsbin/jsbin/releases/tag/v4.0.0) unfortunately (https://github.com/jsbin/jsbin/commit/0e85976ba75d9c9424528edd96717f36b412cb37, May 12th).

But the previous release [`v3.41.10`](https://github.com/jsbin/jsbin/releases/tag/v3.41.10) seems to still work, while requiring node < 0.11 (e.g. `v0.10.48`). I did not have time to fully try it (not sure how to build sqlite), but I can send you a PR to rebase Leaflet customizations on top of that version.

**Pull request merged**
